# Generated by Django 6.0.4 on 2026-05-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='carbs',
            field=models.FloatField(default=0, help_text='Углеводы (г)'),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='fats',
            field=models.FloatField(default=0, help_text='Жиры (г)'),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='fdc_id',
            field=models.IntegerField(blank=True, help_text='ID продукта из FoodData Central', null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='grams',
            field=models.FloatField(default=100, help_text='Количество грамм'),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='meal_group',
            field=models.UUIDField(blank=True, help_text='UUID для группировки продуктов в один приём пищи', null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='protein',
            field=models.FloatField(default=0, help_text='Белки (г)'),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='food_name',
            field=models.CharField(max_length=200),
        ),
    ]
