# Generated by Django 6.0.4 on 2026-05-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_exercise_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='goal_type',
        ),
    ]
