# Generated by Django 6.0.4 on 2026-06-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_remove_workout_goal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='exercise',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
    ]
