# Generated by Django 6.0.4 on 2026-06-12 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_workoutexercise_workout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='accessory_muscles',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='main_muscles',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='part_body',
        ),
    ]
