# Generated by Django 6.0.4 on 2026-06-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_remove_exercise_text_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='comment',
        ),
    ]
