# Generated by Django 6.0.4 on 2026-06-14 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_remove_comment_from_workoutsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musclegroup',
            name='slug',
        ),
    ]
